# Generated by Django 4.0.5 on 2022-10-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0043_addid_date_printed_alter_addid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addid',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
