# Generated by Django 4.0.5 on 2023-07-13 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webid', '0045_alter_addid_status_alter_id_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Davi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devision_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_desc', models.CharField(max_length=250)),
                ('date_send', models.DateField(auto_now_add=True, null=True)),
                ('aprover_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webid.davi')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
