# Generated by Django 4.0.5 on 2023-07-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0046_davi_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='aprover_2',
            field=models.CharField(choices=[('ARDA', 'ARDA'), ('RD', 'RD'), ('PRDM', 'PRMD'), ('LOGISTICS', 'LOGISTICS')], default='Pending', max_length=150),
        ),
        migrations.AddField(
            model_name='letter',
            name='aprover_3',
            field=models.CharField(choices=[('ARDA', 'ARDA'), ('RD', 'RD'), ('PRDM', 'PRMD'), ('LOGISTICS', 'LOGISTICS')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='aprover_1',
            field=models.CharField(choices=[('ARDA', 'ARDA'), ('RD', 'RD'), ('PRDM', 'PRMD'), ('LOGISTICS', 'LOGISTICS')], default='Pending', max_length=150),
        ),
    ]
