# Generated by Django 4.0.5 on 2023-07-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0051_adddivisionww_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
    ]
