# Generated by Django 4.0.5 on 2023-07-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0053_alter_addid_status_alter_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='date_send',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
