# Generated by Django 4.0.5 on 2023-07-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0054_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Dispatch', 'Dispatch'), ('Appropriate Action', 'Appropriate Action'), ('See Remarks', 'See Remarks'), ('File/Reference', 'File/Reference'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Pending', 'Pending'), ('Study/Investigation', 'Study/Investigation'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Approval/Signature', 'Approval Signature')], default='Pending', max_length=150),
        ),
        migrations.AddField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Dispatch', 'Dispatch'), ('Appropriate Action', 'Appropriate Action'), ('See Remarks', 'See Remarks'), ('File/Reference', 'File/Reference'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Pending', 'Pending'), ('Study/Investigation', 'Study/Investigation'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Approval/Signature', 'Approval Signature')], default='Pending', max_length=150),
        ),
        migrations.AddField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Dispatch', 'Dispatch'), ('Appropriate Action', 'Appropriate Action'), ('See Remarks', 'See Remarks'), ('File/Reference', 'File/Reference'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Pending', 'Pending'), ('Study/Investigation', 'Study/Investigation'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Approval/Signature', 'Approval Signature')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='date_send',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
