# Generated by Django 4.0.5 on 2023-07-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0055_letter_stat_1_letter_stat_2_letter_stat_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddivisionww',
            name='division_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adddivisionww',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('Appropriate Action', 'Appropriate Action'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Approval/Signature', 'Approval Signature'), ('Study/Investigation', 'Study/Investigation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Information', 'Information'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('File/Reference', 'File/Reference'), ('See me/ Call me', 'See me/ Call me'), ('Dispatch', 'Dispatch'), ('See Remarks', 'See Remarks'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('Appropriate Action', 'Appropriate Action'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Approval/Signature', 'Approval Signature'), ('Study/Investigation', 'Study/Investigation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Information', 'Information'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('File/Reference', 'File/Reference'), ('See me/ Call me', 'See me/ Call me'), ('Dispatch', 'Dispatch'), ('See Remarks', 'See Remarks'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('Appropriate Action', 'Appropriate Action'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Approval/Signature', 'Approval Signature'), ('Study/Investigation', 'Study/Investigation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Information', 'Information'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('File/Reference', 'File/Reference'), ('See me/ Call me', 'See me/ Call me'), ('Dispatch', 'Dispatch'), ('See Remarks', 'See Remarks'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
