# Generated by Django 4.0.5 on 2023-07-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0056_alter_adddivisionww_division_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('Dispatch', 'Dispatch'), ('Appropriate Action', 'Appropriate Action'), ('Study/Investigation', 'Study/Investigation'), ('Information', 'Information'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Approval/Signature', 'Approval Signature'), ('See Remarks', 'See Remarks'), ('Pending', 'Pending'), ('File/Reference', 'File/Reference'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See me/ Call me', 'See me/ Call me'), ('Rewrite/Redraft', 'Rewrite/Redraft')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('Dispatch', 'Dispatch'), ('Appropriate Action', 'Appropriate Action'), ('Study/Investigation', 'Study/Investigation'), ('Information', 'Information'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Approval/Signature', 'Approval Signature'), ('See Remarks', 'See Remarks'), ('Pending', 'Pending'), ('File/Reference', 'File/Reference'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See me/ Call me', 'See me/ Call me'), ('Rewrite/Redraft', 'Rewrite/Redraft')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('Dispatch', 'Dispatch'), ('Appropriate Action', 'Appropriate Action'), ('Study/Investigation', 'Study/Investigation'), ('Information', 'Information'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Approval/Signature', 'Approval Signature'), ('See Remarks', 'See Remarks'), ('Pending', 'Pending'), ('File/Reference', 'File/Reference'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See me/ Call me', 'See me/ Call me'), ('Rewrite/Redraft', 'Rewrite/Redraft')], default='Pending', max_length=150),
        ),
    ]
