# Generated by Django 4.0.5 on 2023-07-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0057_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddivisionww',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='divisionoffice',
            name='division_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='divisionoffice',
            name='midle_initial',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Approval/Signature', 'Approval Signature'), ('Pending', 'Pending'), ('Study/Investigation', 'Study/Investigation'), ('See Remarks', 'See Remarks'), ('Dispatch', 'Dispatch'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Appropriate Action', 'Appropriate Action'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Information', 'Information'), ('See me/ Call me', 'See me/ Call me'), ('File/Reference', 'File/Reference')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Approval/Signature', 'Approval Signature'), ('Pending', 'Pending'), ('Study/Investigation', 'Study/Investigation'), ('See Remarks', 'See Remarks'), ('Dispatch', 'Dispatch'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Appropriate Action', 'Appropriate Action'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Information', 'Information'), ('See me/ Call me', 'See me/ Call me'), ('File/Reference', 'File/Reference')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Approval/Signature', 'Approval Signature'), ('Pending', 'Pending'), ('Study/Investigation', 'Study/Investigation'), ('See Remarks', 'See Remarks'), ('Dispatch', 'Dispatch'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Appropriate Action', 'Appropriate Action'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Information', 'Information'), ('See me/ Call me', 'See me/ Call me'), ('File/Reference', 'File/Reference')], default='Pending', max_length=150),
        ),
    ]
