# Generated by Django 4.0.5 on 2023-07-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0058_remove_adddivisionww_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Pending', 'Pending'), ('Appropriate Action', 'Appropriate Action'), ('File/Reference', 'File/Reference'), ('See Remarks', 'See Remarks'), ('Approval/Signature', 'Approval Signature'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Study/Investigation', 'Study/Investigation'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Dispatch', 'Dispatch')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Pending', 'Pending'), ('Appropriate Action', 'Appropriate Action'), ('File/Reference', 'File/Reference'), ('See Remarks', 'See Remarks'), ('Approval/Signature', 'Approval Signature'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Study/Investigation', 'Study/Investigation'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Dispatch', 'Dispatch')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Pending', 'Pending'), ('Appropriate Action', 'Appropriate Action'), ('File/Reference', 'File/Reference'), ('See Remarks', 'See Remarks'), ('Approval/Signature', 'Approval Signature'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Study/Investigation', 'Study/Investigation'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Dispatch', 'Dispatch')], default='Pending', max_length=150),
        ),
    ]
