# Generated by Django 4.0.5 on 2023-08-01 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webid', '0059_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Approval/Signature', 'Approval Signature'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Dispatch', 'Dispatch'), ('See me/ Call me', 'See me/ Call me'), ('File/Reference', 'File/Reference'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See Remarks', 'See Remarks'), ('Study/Investigation', 'Study/Investigation'), ('Appropriate Action', 'Appropriate Action'), ('Information', 'Information')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Approval/Signature', 'Approval Signature'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Dispatch', 'Dispatch'), ('See me/ Call me', 'See me/ Call me'), ('File/Reference', 'File/Reference'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See Remarks', 'See Remarks'), ('Study/Investigation', 'Study/Investigation'), ('Appropriate Action', 'Appropriate Action'), ('Information', 'Information')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Approval/Signature', 'Approval Signature'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Dispatch', 'Dispatch'), ('See me/ Call me', 'See me/ Call me'), ('File/Reference', 'File/Reference'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See Remarks', 'See Remarks'), ('Study/Investigation', 'Study/Investigation'), ('Appropriate Action', 'Appropriate Action'), ('Information', 'Information')], default='Pending', max_length=150),
        ),
    ]
