# Generated by Django 4.0.5 on 2023-08-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0060_letter_user_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('See Remarks', 'See Remarks'), ('Pending', 'Pending'), ('Information', 'Information'), ('Dispatch', 'Dispatch'), ('File/Reference', 'File/Reference'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Appropriate Action', 'Appropriate Action'), ('Approval/Signature', 'Approval Signature'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See me/ Call me', 'See me/ Call me'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Study/Investigation', 'Study/Investigation')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('See Remarks', 'See Remarks'), ('Pending', 'Pending'), ('Information', 'Information'), ('Dispatch', 'Dispatch'), ('File/Reference', 'File/Reference'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Appropriate Action', 'Appropriate Action'), ('Approval/Signature', 'Approval Signature'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See me/ Call me', 'See me/ Call me'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Study/Investigation', 'Study/Investigation')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('See Remarks', 'See Remarks'), ('Pending', 'Pending'), ('Information', 'Information'), ('Dispatch', 'Dispatch'), ('File/Reference', 'File/Reference'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Appropriate Action', 'Appropriate Action'), ('Approval/Signature', 'Approval Signature'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See me/ Call me', 'See me/ Call me'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Study/Investigation', 'Study/Investigation')], default='Pending', max_length=150),
        ),
    ]
