# Generated by Django 4.0.5 on 2023-08-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0061_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Study/Investigation', 'Study/Investigation'), ('Dispatch', 'Dispatch'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('See Remarks', 'See Remarks'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Information', 'Information'), ('See me/ Call me', 'See me/ Call me'), ('Pending', 'Pending'), ('Appropriate Action', 'Appropriate Action'), ('File/Reference', 'File/Reference'), ('Approval/Signature', 'Approval Signature')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Study/Investigation', 'Study/Investigation'), ('Dispatch', 'Dispatch'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('See Remarks', 'See Remarks'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Information', 'Information'), ('See me/ Call me', 'See me/ Call me'), ('Pending', 'Pending'), ('Appropriate Action', 'Appropriate Action'), ('File/Reference', 'File/Reference'), ('Approval/Signature', 'Approval Signature')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Study/Investigation', 'Study/Investigation'), ('Dispatch', 'Dispatch'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('See Remarks', 'See Remarks'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Information', 'Information'), ('See me/ Call me', 'See me/ Call me'), ('Pending', 'Pending'), ('Appropriate Action', 'Appropriate Action'), ('File/Reference', 'File/Reference'), ('Approval/Signature', 'Approval Signature')], default='Pending', max_length=150),
        ),
    ]
