# Generated by Django 4.0.5 on 2023-08-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0062_alter_letter_stat_1_alter_letter_stat_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('Approval/Signature', 'Approval Signature'), ('Pending', 'Pending'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action'), ('Dispatch', 'Dispatch'), ('See Remarks', 'See Remarks'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Comment/Recommendation', 'Comment/Recommendation'), ('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('File/Reference', 'File/Reference')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('Approval/Signature', 'Approval Signature'), ('Pending', 'Pending'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action'), ('Dispatch', 'Dispatch'), ('See Remarks', 'See Remarks'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Comment/Recommendation', 'Comment/Recommendation'), ('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('File/Reference', 'File/Reference')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('Approval/Signature', 'Approval Signature'), ('Pending', 'Pending'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action'), ('Dispatch', 'Dispatch'), ('See Remarks', 'See Remarks'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Comment/Recommendation', 'Comment/Recommendation'), ('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('File/Reference', 'File/Reference')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='user',
            field=models.CharField(max_length=250),
        ),
    ]
