# Generated by Django 4.0.5 on 2023-08-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0063_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='bjmptrans_no',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='aprover_1',
            field=models.CharField(blank=True, default='RCDS', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='aprover_2',
            field=models.CharField(blank=True, default='ARDA', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='aprover_3',
            field=models.CharField(blank=True, default='RD', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Dispatch', 'Dispatch'), ('File/Reference', 'File/Reference'), ('See me/ Call me', 'See me/ Call me'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Information', 'Information'), ('Appropriate Action', 'Appropriate Action'), ('Comment/Recommendation', 'Comment/Recommendation'), ('See Remarks', 'See Remarks'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Pending', 'Pending'), ('Approval/Signature', 'Approval Signature')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Dispatch', 'Dispatch'), ('File/Reference', 'File/Reference'), ('See me/ Call me', 'See me/ Call me'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Information', 'Information'), ('Appropriate Action', 'Appropriate Action'), ('Comment/Recommendation', 'Comment/Recommendation'), ('See Remarks', 'See Remarks'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Pending', 'Pending'), ('Approval/Signature', 'Approval Signature')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Dispatch', 'Dispatch'), ('File/Reference', 'File/Reference'), ('See me/ Call me', 'See me/ Call me'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Information', 'Information'), ('Appropriate Action', 'Appropriate Action'), ('Comment/Recommendation', 'Comment/Recommendation'), ('See Remarks', 'See Remarks'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Pending', 'Pending'), ('Approval/Signature', 'Approval Signature')], default='Pending', max_length=150),
        ),
    ]
