# Generated by Django 4.0.5 on 2023-08-13 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webid', '0064_letter_bjmptrans_no_alter_letter_aprover_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddivisionww',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adddivisionww',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('See Remarks', 'See Remarks'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action'), ('Information', 'Information'), ('Approval/Signature', 'Approval Signature'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Study/Investigation', 'Study/Investigation'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Dispatch', 'Dispatch'), ('File/Reference', 'File/Reference'), ('Pending', 'Pending'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('See me/ Call me', 'See me/ Call me')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('See Remarks', 'See Remarks'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action'), ('Information', 'Information'), ('Approval/Signature', 'Approval Signature'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Study/Investigation', 'Study/Investigation'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Dispatch', 'Dispatch'), ('File/Reference', 'File/Reference'), ('Pending', 'Pending'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('See me/ Call me', 'See me/ Call me')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('See Remarks', 'See Remarks'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action'), ('Information', 'Information'), ('Approval/Signature', 'Approval Signature'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Study/Investigation', 'Study/Investigation'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Dispatch', 'Dispatch'), ('File/Reference', 'File/Reference'), ('Pending', 'Pending'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('See me/ Call me', 'See me/ Call me')], default='Pending', max_length=150),
        ),
    ]
