# Generated by Django 4.0.5 on 2023-08-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0065_adddivisionww_address_alter_adddivisionww_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddivisionww',
            name='address',
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Rewrite/Redraft', 'Rewrite/Redraft'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Approval/Signature', 'Approval Signature'), ('See Remarks', 'See Remarks'), ('Appropriate Action', 'Appropriate Action'), ('Comment/Recommendation', 'Comment/Recommendation'), ('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Study/Investigation', 'Study/Investigation'), ('Dispatch', 'Dispatch'), ('Pending', 'Pending'), ('File/Reference', 'File/Reference')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Rewrite/Redraft', 'Rewrite/Redraft'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Approval/Signature', 'Approval Signature'), ('See Remarks', 'See Remarks'), ('Appropriate Action', 'Appropriate Action'), ('Comment/Recommendation', 'Comment/Recommendation'), ('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Study/Investigation', 'Study/Investigation'), ('Dispatch', 'Dispatch'), ('Pending', 'Pending'), ('File/Reference', 'File/Reference')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Rewrite/Redraft', 'Rewrite/Redraft'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Approval/Signature', 'Approval Signature'), ('See Remarks', 'See Remarks'), ('Appropriate Action', 'Appropriate Action'), ('Comment/Recommendation', 'Comment/Recommendation'), ('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Study/Investigation', 'Study/Investigation'), ('Dispatch', 'Dispatch'), ('Pending', 'Pending'), ('File/Reference', 'File/Reference')], default='Pending', max_length=150),
        ),
    ]
