# Generated by Django 4.0.5 on 2023-08-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0066_remove_adddivisionww_address_alter_addid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='images/signature'),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('See me/ Call me', 'See me/ Call me'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Approval/Signature', 'Approval Signature'), ('Appropriate Action', 'Appropriate Action'), ('File/Reference', 'File/Reference'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Study/Investigation', 'Study/Investigation'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Information', 'Information'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See Remarks', 'See Remarks'), ('Pending', 'Pending'), ('Dispatch', 'Dispatch')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('See me/ Call me', 'See me/ Call me'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Approval/Signature', 'Approval Signature'), ('Appropriate Action', 'Appropriate Action'), ('File/Reference', 'File/Reference'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Study/Investigation', 'Study/Investigation'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Information', 'Information'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See Remarks', 'See Remarks'), ('Pending', 'Pending'), ('Dispatch', 'Dispatch')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('See me/ Call me', 'See me/ Call me'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Approval/Signature', 'Approval Signature'), ('Appropriate Action', 'Appropriate Action'), ('File/Reference', 'File/Reference'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Study/Investigation', 'Study/Investigation'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Information', 'Information'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See Remarks', 'See Remarks'), ('Pending', 'Pending'), ('Dispatch', 'Dispatch')], default='Pending', max_length=150),
        ),
    ]
