# Generated by Django 4.0.5 on 2023-08-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0067_alter_addid_status_alter_employee_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('See me/ Call me', 'See me/ Call me'), ('Pending', 'Pending'), ('See Remarks', 'See Remarks'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Dispatch', 'Dispatch'), ('Appropriate Action', 'Appropriate Action'), ('Comment/Recommendation', 'Comment/Recommendation'), ('File/Reference', 'File/Reference'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Approval/Signature', 'Approval Signature'), ('Information', 'Information'), ('Prepare Speech/Message', 'Prepare Speech/Message')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('See me/ Call me', 'See me/ Call me'), ('Pending', 'Pending'), ('See Remarks', 'See Remarks'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Dispatch', 'Dispatch'), ('Appropriate Action', 'Appropriate Action'), ('Comment/Recommendation', 'Comment/Recommendation'), ('File/Reference', 'File/Reference'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Approval/Signature', 'Approval Signature'), ('Information', 'Information'), ('Prepare Speech/Message', 'Prepare Speech/Message')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('See me/ Call me', 'See me/ Call me'), ('Pending', 'Pending'), ('See Remarks', 'See Remarks'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Dispatch', 'Dispatch'), ('Appropriate Action', 'Appropriate Action'), ('Comment/Recommendation', 'Comment/Recommendation'), ('File/Reference', 'File/Reference'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Approval/Signature', 'Approval Signature'), ('Information', 'Information'), ('Prepare Speech/Message', 'Prepare Speech/Message')], default='Pending', max_length=150),
        ),
    ]
