# Generated by Django 4.0.5 on 2023-08-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0068_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='letter_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/letters'),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Reply Direct to Writer', 'Reply Direct to Writer'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Dispatch', 'Dispatch'), ('Pending', 'Pending'), ('Appropriate Action', 'Appropriate Action'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Study/Investigation', 'Study/Investigation'), ('See Remarks', 'See Remarks'), ('File/Reference', 'File/Reference'), ('Approval/Signature', 'Approval Signature')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Reply Direct to Writer', 'Reply Direct to Writer'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Dispatch', 'Dispatch'), ('Pending', 'Pending'), ('Appropriate Action', 'Appropriate Action'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Study/Investigation', 'Study/Investigation'), ('See Remarks', 'See Remarks'), ('File/Reference', 'File/Reference'), ('Approval/Signature', 'Approval Signature')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Reply Direct to Writer', 'Reply Direct to Writer'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('See me/ Call me', 'See me/ Call me'), ('Information', 'Information'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Dispatch', 'Dispatch'), ('Pending', 'Pending'), ('Appropriate Action', 'Appropriate Action'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Study/Investigation', 'Study/Investigation'), ('See Remarks', 'See Remarks'), ('File/Reference', 'File/Reference'), ('Approval/Signature', 'Approval Signature')], default='Pending', max_length=150),
        ),
    ]
