# Generated by Django 4.0.5 on 2023-08-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0069_letter_letter_pdf_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_pdf',
            field=models.FileField(blank=True, null=True, upload_to='images/signature'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('Pending', 'Pending'), ('File/Reference', 'File/Reference'), ('See Remarks', 'See Remarks'), ('Information', 'Information'), ('Approval/Signature', 'Approval Signature'), ('See me/ Call me', 'See me/ Call me'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Study/Investigation', 'Study/Investigation'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Dispatch', 'Dispatch'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('Pending', 'Pending'), ('File/Reference', 'File/Reference'), ('See Remarks', 'See Remarks'), ('Information', 'Information'), ('Approval/Signature', 'Approval Signature'), ('See me/ Call me', 'See me/ Call me'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Study/Investigation', 'Study/Investigation'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Dispatch', 'Dispatch'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('Pending', 'Pending'), ('File/Reference', 'File/Reference'), ('See Remarks', 'See Remarks'), ('Information', 'Information'), ('Approval/Signature', 'Approval Signature'), ('See me/ Call me', 'See me/ Call me'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Study/Investigation', 'Study/Investigation'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Dispatch', 'Dispatch'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action')], default='Pending', max_length=150),
        ),
    ]
