# Generated by Django 4.0.5 on 2023-08-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0070_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Dispatch', 'Dispatch'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('See me/ Call me', 'See me/ Call me'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Pending', 'Pending'), ('Approval/Signature', 'Approval Signature'), ('File/Reference', 'File/Reference'), ('See Remarks', 'See Remarks'), ('Information', 'Information'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Dispatch', 'Dispatch'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('See me/ Call me', 'See me/ Call me'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Pending', 'Pending'), ('Approval/Signature', 'Approval Signature'), ('File/Reference', 'File/Reference'), ('See Remarks', 'See Remarks'), ('Information', 'Information'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('Comment/Recommendation', 'Comment/Recommendation'), ('Dispatch', 'Dispatch'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('See me/ Call me', 'See me/ Call me'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Pending', 'Pending'), ('Approval/Signature', 'Approval Signature'), ('File/Reference', 'File/Reference'), ('See Remarks', 'See Remarks'), ('Information', 'Information'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action')], default='Pending', max_length=150),
        ),
    ]
