# Generated by Django 4.0.5 on 2023-08-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0071_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/letters'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('Approval/Signature', 'Approval Signature'), ('See me/ Call me', 'See me/ Call me'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action'), ('Pending', 'Pending'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Information', 'Information'), ('Dispatch', 'Dispatch'), ('See Remarks', 'See Remarks'), ('Comment/Recommendation', 'Comment/Recommendation'), ('File/Reference', 'File/Reference')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('Approval/Signature', 'Approval Signature'), ('See me/ Call me', 'See me/ Call me'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action'), ('Pending', 'Pending'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Information', 'Information'), ('Dispatch', 'Dispatch'), ('See Remarks', 'See Remarks'), ('Comment/Recommendation', 'Comment/Recommendation'), ('File/Reference', 'File/Reference')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Study/Investigation', 'Study/Investigation'), ('Approval/Signature', 'Approval Signature'), ('See me/ Call me', 'See me/ Call me'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('Appropriate Action', 'Appropriate Action'), ('Pending', 'Pending'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Information', 'Information'), ('Dispatch', 'Dispatch'), ('See Remarks', 'See Remarks'), ('Comment/Recommendation', 'Comment/Recommendation'), ('File/Reference', 'File/Reference')], default='Pending', max_length=150),
        ),
    ]
