# Generated by Django 4.0.5 on 2023-08-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0072_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_person',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_person_no',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_no',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='midle_initial',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='philhealth_no',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sss_no',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tin',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_desc',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sender',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('File/Reference', 'File/Reference'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See Remarks', 'See Remarks'), ('Study/Investigation', 'Study/Investigation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Approval/Signature', 'Approval Signature'), ('See me/ Call me', 'See me/ Call me'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Appropriate Action', 'Appropriate Action'), ('Dispatch', 'Dispatch'), ('Information', 'Information'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('File/Reference', 'File/Reference'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See Remarks', 'See Remarks'), ('Study/Investigation', 'Study/Investigation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Approval/Signature', 'Approval Signature'), ('See me/ Call me', 'See me/ Call me'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Appropriate Action', 'Appropriate Action'), ('Dispatch', 'Dispatch'), ('Information', 'Information'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Comment/Recommendation', 'Comment/Recommendation'), ('File/Reference', 'File/Reference'), ('Prepare Speech/Message', 'Prepare Speech/Message'), ('See Remarks', 'See Remarks'), ('Study/Investigation', 'Study/Investigation'), ('Rewrite/Redraft', 'Rewrite/Redraft'), ('Approval/Signature', 'Approval Signature'), ('See me/ Call me', 'See me/ Call me'), ('Reply Direct to Writer', 'Reply Direct to Writer'), ('Appropriate Action', 'Appropriate Action'), ('Dispatch', 'Dispatch'), ('Information', 'Information'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
