# Generated by Django 4.0.5 on 2023-08-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0075_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='action_request',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
