# Generated by Django 4.0.5 on 2023-09-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0077_alter_addid_status_alter_id_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='date_updated_aprover_1',
            field=models.DateTimeField(auto_now=True, verbose_name='stat_1'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
