# Generated by Django 4.0.5 on 2023-09-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0079_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='date_updated_aprover_1',
        ),
        migrations.AddField(
            model_name='letter',
            name='date_aprov_1',
            field=models.DateTimeField(auto_now=True, verbose_name=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150)),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
    ]
