# Generated by Django 4.0.5 on 2023-09-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0080_remove_letter_date_updated_aprover_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='date_aprov_1',
            field=models.DateTimeField(auto_now=True, verbose_name=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=150)),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
