# Generated by Django 4.0.5 on 2023-09-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0085_letter_date_aprov_2_letter_date_aprov_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='comment_arda',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='comment_rcds',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='comment_rd',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
    ]
