# Generated by Django 4.0.5 on 2024-04-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0086_letter_comment_arda_letter_comment_rcds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddivisionww',
            name='division_name',
            field=models.CharField(choices=[('RID', 'RID'), ('WD', 'WD'), ('RIPD', 'RIPD'), ('LEGAL', 'LEGAL'), ('HRDD', 'HRDD'), ('RESJO', 'RESJO'), ('FINANCE', 'FINANCE'), ('OPERATION', 'OPERATION'), ('LOGISTICS', 'LOGISTICS'), ('PRMD', 'PRMD'), ('CRS', 'CRS'), ('ICTMD', 'ICTMD'), ('GSO', 'GSO'), ('HSD', 'HSD'), ('RSAO', 'RSAO'), ('CHOOSE DIVISION', 'CHOOSE DIVISION')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
    ]
