# Generated by Django 5.0.4 on 2024-05-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0092_alter_addid_status_alter_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
    ]
