# Generated by Django 5.0.4 on 2024-05-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0094_sampleletter_samplenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='samplenotification',
            name='user',
            field=models.CharField(max_length=250),
        ),
    ]
