# Generated by Django 5.0.4 on 2024-07-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0096_samplenotification_bjmptrans_no_alter_addid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='aprover_4',
            field=models.CharField(blank=True, default='ARDO', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='comment_ardo',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='date_aprov_4',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='stat_4',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Edit', 'For Edit'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
    ]
