# Generated by Django 5.0.4 on 2024-08-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0101_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_4',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
    ]
