# Generated by Django 5.0.4 on 2024-08-21 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0102_alter_addid_status_alter_id_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_4',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FCMDevice',
        ),
    ]
