# Generated by Django 5.0.4 on 2024-08-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0103_alter_letter_stat_1_alter_letter_stat_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddivisionww',
            name='rank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Disapproved', 'Disapproved'), ('Official Business', 'Official Business'), ('On Leave', 'On Leave'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Disapproved', 'Disapproved'), ('Official Business', 'Official Business'), ('On Leave', 'On Leave'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Disapproved', 'Disapproved'), ('Official Business', 'Official Business'), ('On Leave', 'On Leave'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_4',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Disapproved', 'Disapproved'), ('Official Business', 'Official Business'), ('On Leave', 'On Leave'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
    ]
