# Generated by Django 5.0.4 on 2024-09-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0104_adddivisionww_rank_alter_addid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddivisionww',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='images/signature'),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Official Business', 'Official Business'), ('Approved', 'Approved'), ('On Leave', 'On Leave'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Official Business', 'Official Business'), ('Approved', 'Approved'), ('On Leave', 'On Leave'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Official Business', 'Official Business'), ('Approved', 'Approved'), ('On Leave', 'On Leave'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_4',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Official Business', 'Official Business'), ('Approved', 'Approved'), ('On Leave', 'On Leave'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
