# Generated by Django 5.0.4 on 2025-01-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0105_adddivisionww_signature_alter_addid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='dispatch',
            field=models.CharField(choices=[('Dispatched', 'Dispatched'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('For Edit', 'For Edit'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Official Business', 'Official Business'), ('On Leave', 'On Leave')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Official Business', 'Official Business'), ('On Leave', 'On Leave')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Official Business', 'Official Business'), ('On Leave', 'On Leave')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_4',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Official Business', 'Official Business'), ('On Leave', 'On Leave')], default='Pending', max_length=150),
        ),
    ]
