# Generated by Django 5.0.4 on 2025-02-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0106_letter_dispatch_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Official Business', 'Official Business'), ('On Leave', 'On Leave'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Official Business', 'Official Business'), ('On Leave', 'On Leave'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Official Business', 'Official Business'), ('On Leave', 'On Leave'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_4',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Official Business', 'Official Business'), ('On Leave', 'On Leave'), ('Disapproved', 'Disapproved')], default='Pending', max_length=150),
        ),
    ]
