# Generated by Django 5.0.4 on 2025-05-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0107_letter_updated_date_alter_addid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('For Edit', 'For Edit'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='dispatch',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Official Business', 'Official Business'), ('Disapproved', 'Disapproved'), ('On Leave', 'On Leave'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Official Business', 'Official Business'), ('Disapproved', 'Disapproved'), ('On Leave', 'On Leave'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Official Business', 'Official Business'), ('Disapproved', 'Disapproved'), ('On Leave', 'On Leave'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_4',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Official Business', 'Official Business'), ('Disapproved', 'Disapproved'), ('On Leave', 'On Leave'), ('Approved', 'Approved')], default='Pending', max_length=150),
        ),
    ]
