# Generated by Django 5.0.4 on 2025-05-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0108_alter_addid_status_alter_id_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='dispatch',
            field=models.CharField(choices=[('Dispatched', 'Dispatched'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('Approved', 'Approved'), ('On Leave', 'On Leave'), ('Disapproved', 'Disapproved'), ('Official Business', 'Official Business'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('Approved', 'Approved'), ('On Leave', 'On Leave'), ('Disapproved', 'Disapproved'), ('Official Business', 'Official Business'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('Approved', 'Approved'), ('On Leave', 'On Leave'), ('Disapproved', 'Disapproved'), ('Official Business', 'Official Business'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_4',
            field=models.CharField(choices=[('Approved', 'Approved'), ('On Leave', 'On Leave'), ('Disapproved', 'Disapproved'), ('Official Business', 'Official Business'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
