# Generated by Django 5.0.4 on 2026-04-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webid', '0112_letter_mega_file_id_alter_addid_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='mega_file_id',
        ),
        migrations.AlterField(
            model_name='addid',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='id',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('For Edit', 'For Edit')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_1',
            field=models.CharField(choices=[('On Leave', 'On Leave'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved'), ('Official Business', 'Official Business')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_2',
            field=models.CharField(choices=[('On Leave', 'On Leave'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved'), ('Official Business', 'Official Business')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_3',
            field=models.CharField(choices=[('On Leave', 'On Leave'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved'), ('Official Business', 'Official Business')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='letter',
            name='stat_4',
            field=models.CharField(choices=[('On Leave', 'On Leave'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved'), ('Official Business', 'Official Business')], default='Pending', max_length=150),
        ),
    ]
